sudo:
  false

language:
  php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

cache:
  directories:
  - vendor

before_script:
  - composer install --dev --no-interaction --prefer-source
  - phpenv development

script:
  - vendor/bin/phpunit --configuration phpunit.xml test
